name: devsecops-pipeline
on: [push]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'node:20-alpine'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
